### ISSUE TITLE
Missing install procedure in "Install and Build procedure"

### ISSUE THREAD

**Issue by xdev-x** [wookey-project/wookeypedia#2]
On the page "https://wookey-project.github.io/tataouine/build.html#buildprocedure", the main title is "Install and Build procedure".

I think the install procedure is missing (use of the repo tool) + an abstract of the architecture of the Tatouine SDK (a link to https://wookey-project.github.io/tataouine/repo.html should be enough).

**Comment by PThierry** [comment]
Corrected in SDK v1.0.3
