### ISSUE TITLE
Link to Kconfig-frontends down

### ISSUE THREAD

**Issue by xdev-x** [wookey-project/wookeypedia#3]
The link to Kconfig-frontends is down on "https://wookey-project.github.io/tataouine/deps.html#dependencies".

**Comment by PThierry** [comment]
Thanks for the information!

We have seen that the kconfig-frontend webstite has just being closed. We are currently updating the SDK to support others kconfig parsers like kconfiglib python module.

We will publish the patchset as soon as possible.
